# Generated by Django 4.2.4 on 2023-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=15)),
                ("nome_empresa", models.CharField(max_length=15)),
                ("categoria_empresa", models.CharField(max_length=150)),
                ("quitado", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Stand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localizacao", models.CharField(max_length=150)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
